### ISSUE TITLE
爬到一半会提示: TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by AudareLesdent** [TheSlientnight/bilibili_crawler#1]
Traceback (most recent call last):
  File "/home/jky/anaconda3/envs/bilicrawler/lib/python3.7/site-packages/threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "/home/jky/program/github/bilibilicrawler/bilibili_crawler-master/common/get_urls.py", line 33, in get_comment
    comment_list.extend(comment)

**Comment by TheSlientnight** [comment]
你好，可以给到对应的地址吗，现在看来好像是jsonpath判空了，想看看是不是因为评论问题导致的，如果能提供对应的数据可以更快的修复当前问题

**Comment by TheSlientnight** [comment]
你好，问题已经修复，请重新fork或pull request或pull代码
